# Fichier Docker Compose pour l'environnement de développement.
version: '3.8'

services:
  # Base de données
  mongodb:
    image: mongo:6.0
    container_name: erp-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      # Utilisé pour l'initialisation de la base de données.
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-password}
    networks:
      - erp-network

  # Cache
  redis:
    image: redis:7-alpine
    container_name: erp-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - erp-network

  # API Backend
  server:
    build: ./server
    container_name: erp-server-dev
    restart: unless-stopped
    env_file:
      - ./server/.env # Charge les variables locales par défaut.
    environment:
      # Surcharge les variables critiques pour la communication entre conteneurs.
      - MONGODB_URI=mongodb://${DB_USER:-admin}:${DB_PASS:-password}@mongodb:27017/erp_senegal?authSource=admin
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app         # Hot-reloading du code source.
      - /app/node_modules   # Isole les node_modules du conteneur.
    depends_on:
      - mongodb
      - redis
    networks:
      - erp-network

  # Application Frontend
  client:
    build: ./client
    container_name: erp-client-dev
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      # Le port par défaut de Vite est 5173, et non 3000.
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - erp-network

# Volumes pour la persistance des données.
volumes:
  mongodb_data:
  redis_data:

# Réseau partagé pour la communication entre services.
networks:
  erp-network:
    driver: bridge